// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.30.2
// source: msg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "msg";

export enum MsgId {
  NULL = 0,
  /** Msg_S2C_Msg - 回应协议 */
  Msg_S2C_Msg = 100,
  /** User_C2S_Login - 登录 */
  User_C2S_Login = 100100,
  /** User_S2C_Login - 登录返回 */
  User_S2C_Login = 200100,
  UNRECOGNIZED = -1,
}

export function msgIdFromJSON(object: any): MsgId {
  switch (object) {
    case 0:
    case "NULL":
      return MsgId.NULL;
    case 100:
    case "Msg_S2C_Msg":
      return MsgId.Msg_S2C_Msg;
    case 100100:
    case "User_C2S_Login":
      return MsgId.User_C2S_Login;
    case 200100:
    case "User_S2C_Login":
      return MsgId.User_S2C_Login;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MsgId.UNRECOGNIZED;
  }
}

export function msgIdToJSON(object: MsgId): string {
  switch (object) {
    case MsgId.NULL:
      return "NULL";
    case MsgId.Msg_S2C_Msg:
      return "Msg_S2C_Msg";
    case MsgId.User_C2S_Login:
      return "User_C2S_Login";
    case MsgId.User_S2C_Login:
      return "User_S2C_Login";
    case MsgId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MsgCode {
  /** SUCC - 成功 */
  SUCC = 0,
  /** ERROR - 失败 */
  ERROR = -1,
}

export function msgCodeFromJSON(object: any): MsgCode {
  switch (object) {
    case 0:
    case "SUCC":
      return MsgCode.SUCC;
    case -1:
    case "ERROR":
      return MsgCode.ERROR;
    default:
      return MsgCode.ERROR;
  }
}

export function msgCodeToJSON(object: MsgCode): string {
  switch (object) {
    case MsgCode.SUCC:
      return "SUCC";
    case MsgCode.ERROR:
      return "ERROR";
    default:
      return "ERROR";
  }
}

export enum PlatformType {
  /** H5 - 本地 */
  H5 = 0,
  /** WX_MINI - 微信小游戏 */
  WX_MINI = 1,
  UNRECOGNIZED = -1,
}

export function platformTypeFromJSON(object: any): PlatformType {
  switch (object) {
    case 0:
    case "H5":
      return PlatformType.H5;
    case 1:
    case "WX_MINI":
      return PlatformType.WX_MINI;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PlatformType.UNRECOGNIZED;
  }
}

export function platformTypeToJSON(object: PlatformType): string {
  switch (object) {
    case PlatformType.H5:
      return "H5";
    case PlatformType.WX_MINI:
      return "WX_MINI";
    case PlatformType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface S2C_Msg {
  code: MsgCode;
  mId: MsgId;
  message: string;
}

function createBaseS2C_Msg(): S2C_Msg {
  return { code: 0, mId: 0, message: "" };
}

export const S2C_Msg: MessageFns<S2C_Msg> = {
  encode(message: S2C_Msg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.mId !== 0) {
      writer.uint32(16).int32(message.mId);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S2C_Msg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS2C_Msg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mId = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S2C_Msg {
    return {
      code: isSet(object.code) ? msgCodeFromJSON(object.code) : 0,
      mId: isSet(object.mId) ? msgIdFromJSON(object.mId) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: S2C_Msg): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = msgCodeToJSON(message.code);
    }
    if (message.mId !== 0) {
      obj.mId = msgIdToJSON(message.mId);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S2C_Msg>, I>>(base?: I): S2C_Msg {
    return S2C_Msg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S2C_Msg>, I>>(object: I): S2C_Msg {
    const message = createBaseS2C_Msg();
    message.code = object.code ?? 0;
    message.mId = object.mId ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
